export interface ModelInfo {
  id: string;
  name: string;
  size: string;
  description: string;
}

export interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface BonsaiAPI {
  isNativeAvailable(): boolean;
  loadModel(modelId: string): Promise<void>;
  generate(messages: { role: 'user' | 'assistant'; content: string }[], onToken: (token: string) => void): Promise<string>;
  stopGeneration(): Promise<void>;
}

/**
 * Mock API for web development without iOS native plugin.
 * Simulates streaming responses with realistic delays.
 */
class MockBonsaiAPI implements BonsaiAPI {
  isNativeAvailable() { return false; }

  async loadModel(_modelId: string): Promise<void> {
    // Simulate model loading delay
    await new Promise(r => setTimeout(r, 800));
  }

  async generate(
    messages: { role: 'user' | 'assistant'; content: string }[],
    onToken: (token: string) => void,
  ): Promise<string> {
    const lastUserMsg = [...messages].reverse().find(m => m.role === 'user')?.content ?? '';

    // Simulate thinking delay
    await new Promise(r => setTimeout(r, 300 + Math.random() * 500));

    const response = this.generateMockResponse(lastUserMsg);
    let full = '';

    for (const char of response) {
      full += char;
      onToken(char);
      await new Promise(r => setTimeout(r, 15 + Math.random() * 25));
    }

    return full;
  }

  async stopGeneration(): Promise<void> {}

  private generateMockResponse(prompt: string): string {
    const lower = prompt.toLowerCase();

    if (lower.includes('hello') || lower.includes('hi') || lower.includes('hey')) {
      return "Hello! I'm Bonsai, running locally on your device via MLX. I'm a compact but capable language model using 1-bit quantization. How can I help you today?";
    }

    if (lower.includes('who are you') || lower.includes('what are you')) {
      return "I'm Bonsai, a 1-bit quantized language model by PrismML. I'm running entirely on-device using Apple's MLX framework with custom 1-bit dequantization kernels. This means:\n\n• No data leaves your device\n• No API keys needed\n• No network required\n• Fully private inference\n\nI come in three sizes: 1.7B, 4B, and 8B parameters, compressed down to as little as 0.27GB thanks to 1-bit quantization.";
    }

    if (lower.includes('explain') || lower.includes('what is') || lower.includes('how does')) {
      return `That's a great question! Here's what I know about "${prompt.slice(0, 50)}..."\n\nIn mock mode, I generate predefined responses. When running on a real iOS device with the Bonsai MLX engine, I'll provide actual model-generated responses.\n\nTo get real inference:\n1. Build the iOS app with Xcode\n2. Run on an Apple Silicon device\n3. The Bonsai model loads from HuggingFace\n4. Chat away!`;
    }

    return `I received your message: "${prompt}"\n\nThis is a mock response running in the browser. On a real iOS device with the native Bonsai plugin, this would be generated by the Bonsai-${8}B-mlx-1bit model running locally via MLX.\n\nTry asking me "who are you" or "hello" for different mock responses!`;
  }
}

/**
 * Native API using Capacitor plugin bridge to iOS.
 */
class NativeBonsaiAPI implements BonsaiAPI {
  private plugin: any;

  constructor() {
    this.plugin = (window as any).Capacitor?.isNativePlatform()
      ? (window as any).Capacitor.Plugins?.BonsaiPlugin
      : null;
  }

  isNativeAvailable(): boolean {
    return !!this.plugin;
  }

  async loadModel(modelId: string): Promise<void> {
    await this.plugin.loadModel({ modelId });
  }

  async generate(
    messages: { role: 'user' | 'assistant'; content: string }[],
    onToken: (token: string) => void,
  ): Promise<string> {
    const { result } = await this.plugin.generate({
      messages,
      stream: true,
    });

    return new Promise((resolve, reject) => {
      const listener = await this.plugin.addListener('streamToken', (event: any) => {
        if (event.done) {
          listener.remove();
          resolve(event.fullText);
        } else {
          onToken(event.token);
        }
      });

      // Timeout fallback
      setTimeout(() => {
        listener.remove();
        reject(new Error('Generation timed out'));
      }, 120_000);
    });
  }

  async stopGeneration(): Promise<void> {
    await this.plugin.stopGeneration();
  }
}

export function getBonsaiAPI(): BonsaiAPI {
  try {
    const native = new NativeBonsaiAPI();
    if (native.isNativeAvailable()) return native;
  } catch {}
  return new MockBonsaiAPI();
}
