export interface ModelInfo {
  id: string;
  name: string;
  size: string;
  description: string;
}

export interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface BonsaiAPI {
  isNativeAvailable(): boolean;
  loadModel(modelId: string): Promise<void>;
  generate(messages: { role: 'user' | 'assistant'; content: string }[], onToken: (token: string) => void, systemPrompt?: string): Promise<string>;
  stopGeneration(): Promise<void>;
}

/**
 * Mock API for web development without iOS native plugin.
 * Simulates streaming responses with realistic delays.
 */
class MockBonsaiAPI implements BonsaiAPI {
  isNativeAvailable() { return false; }

  async loadModel(_modelId: string): Promise<void> {
    // Simulate model loading delay
    await new Promise(r => setTimeout(r, 800));
  }

  async generate(
    messages: { role: 'user' | 'assistant'; content: string }[],
    onToken: (token: string) => void,
    _systemPrompt?: string,
  ): Promise<string> {
    const lastUserMsg = [...messages].reverse().find(m => m.role === 'user')?.content ?? '';

    // Simulate thinking delay
    await new Promise(r => setTimeout(r, 300 + Math.random() * 500));

    const response = this.generateMockResponse(lastUserMsg);
    let full = '';

    for (const char of response) {
      full += char;
      onToken(char);
      await new Promise(r => setTimeout(r, 15 + Math.random() * 25));
    }

    return full;
  }

  async stopGeneration(): Promise<void> {}

  private generateMockResponse(prompt: string): string {
    const lower = prompt.toLowerCase();

    if (lower.includes('hello') || lower.includes('hi') || lower.includes('hey')) {
      return "Hello! I'm Bonsai, running locally on your device via MLX. I'm a compact but capable language model using 1-bit quantization. How can I help you today?";
    }

    if (lower.includes('who are you') || lower.includes('what are you')) {
      return "I'm Bonsai, a 1-bit quantized language model by PrismML. I'm running entirely on-device using Apple's MLX framework with custom 1-bit dequantization kernels. This means:\n\n• No data leaves your device\n• No API keys needed\n• No network required\n• Fully private inference\n\nI come in three sizes: 1.7B, 4B, and 8B parameters, compressed down to as little as 0.27GB thanks to 1-bit quantization.";
    }

    if (lower.includes('explain') || lower.includes('what is') || lower.includes('how does')) {
      return `That's a great question! Here's what I know about "${prompt.slice(0, 50)}..."\n\nIn mock mode, I generate predefined responses. When running on a real iOS device with the Bonsai MLX engine, I'll provide actual model-generated responses.\n\nTo get real inference:\n1. Build the iOS app with Xcode\n2. Run on an Apple Silicon device\n3. The Bonsai model loads from HuggingFace\n4. Chat away!`;
    }

    return `I received your message: "${prompt}"\n\nThis is a mock response running in the browser. On a real iOS device with the native Bonsai plugin, this would be generated by the Bonsai-${8}B-mlx-1bit model running locally via MLX.\n\nTry asking me "who are you" or "hello" for different mock responses!`;
  }
}

/**
 * Native API using Capacitor plugin bridge to iOS.
 */
class NativeBonsaiAPI implements BonsaiAPI {
  private plugin: any;

  constructor() {
    this.plugin = (window as any).Capacitor?.isNativePlatform()
      ? (window as any).Capacitor.Plugins?.BonsaiPlugin
      : null;
  }

  isNativeAvailable(): boolean {
    return !!this.plugin;
  }

  async loadModel(modelId: string): Promise<void> {
    await this.plugin.loadModel({ modelId });
  }

  async generate(
    messages: { role: 'user' | 'assistant'; content: string }[],
    onToken: (token: string) => void,
    systemPrompt?: string,
  ): Promise<string> {
    const { result: _r } = await this.plugin.generate({
      messages,
      stream: true,
      systemPrompt,
    });

    return new Promise(async (resolve, reject) => {
      const listener = await this.plugin.addListener('streamToken', (event: any) => {
        if (event.done) {
          listener.remove();
          resolve(event.fullText);
        } else {
          onToken(event.token);
        }
      });

      // Timeout fallback
      setTimeout(() => {
        listener.remove();
        reject(new Error('Generation timed out'));
      }, 120_000);
    });
  }

  async stopGeneration(): Promise<void> {
    await this.plugin.stopGeneration();
  }
}

/**
 * HTTP API for llama.cpp server (OpenAI-compatible).
 * Works on macOS/web when a llama-server is running.
 */
export class HttpBonsaiAPI implements BonsaiAPI {
  private baseUrl: string;
  private connected = false;
  private abortController: AbortController | null = null;

  constructor(baseUrl = 'http://localhost:8088') {
    this.baseUrl = baseUrl;
  }

  isNativeAvailable(): boolean {
    return false;
  }

  isServerAvailable(): boolean {
    return this.connected;
  }

  getBaseUrl(): string {
    return this.baseUrl;
  }

  async setBaseUrl(url: string): Promise<void> {
    this.baseUrl = url;
    await this.checkConnection();
  }

  async checkConnection(): Promise<boolean> {
    try {
      const res = await fetch(`${this.baseUrl}/health`, { signal: AbortSignal.timeout(3000) });
      this.connected = res.ok;
    } catch {
      this.connected = false;
    }
    return this.connected;
  }

  async loadModel(_modelId: string): Promise<void> {
    // llama.cpp server loads model at startup; just verify connection
    const ok = await this.checkConnection();
    if (!ok) throw new Error(`Cannot connect to llama.cpp server at ${this.baseUrl}. Is it running?`);
  }

  async generate(
    messages: { role: 'user' | 'assistant'; content: string }[],
    onToken: (token: string) => void,
    systemPrompt?: string,
  ): Promise<string> {
    this.abortController = new AbortController();

    const systemMsg: Message = {
      role: 'system',
      content: systemPrompt || 'You are Bonsai, a helpful AI assistant running locally via llama.cpp.',
    };

    const res = await fetch(`${this.baseUrl}/v1/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        messages: [systemMsg, ...messages],
        stream: true,
        model: 'bonsai',
      }),
      signal: this.abortController.signal,
    });

    if (!res.ok) {
      throw new Error(`Server error: ${res.status} ${res.statusText}`);
    }

    this.connected = true;
    let full = '';

    const reader = res.body?.getReader();
    if (!reader) throw new Error('No response body');

    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop() ?? '';

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || !trimmed.startsWith('data: ')) continue;
        const data = trimmed.slice(6);
        if (data === '[DONE]') continue;

        try {
          const json = JSON.parse(data);
          const token = json.choices?.[0]?.delta?.content ?? '';
          if (token) {
            full += token;
            onToken(token);
          }
        } catch {}
      }
    }

    this.abortController = null;
    return full;
  }

  async stopGeneration(): Promise<void> {
    this.abortController?.abort();
    this.abortController = null;
  }
}

export type APIType = 'native' | 'http' | 'mock';

export interface APIStatus {
  type: APIType;
  label: string;
  serverUrl?: string;
  connected: boolean;
}

export function getBonsaiAPI(serverUrl?: string): { api: BonsaiAPI; status: APIStatus } {
  // Try native (Capacitor iOS)
  try {
    const native = new NativeBonsaiAPI();
    if (native.isNativeAvailable()) {
      return { api: native, status: { type: 'native', label: 'Connected to native', connected: true } };
    }
  } catch {}

  // Try HTTP (llama.cpp server)
  const http = new HttpBonsaiAPI(serverUrl);
  return {
    api: http,
    status: { type: 'http', label: 'Server mode', serverUrl: http.getBaseUrl(), connected: false },
  };
}

/**
 * Legacy export for backward compat (returns MockBonsaiAPI).
 */
export function getBonsaiAPICompat(): BonsaiAPI {
  try {
    const native = new NativeBonsaiAPI();
    if (native.isNativeAvailable()) return native;
  } catch {}
  return new MockBonsaiAPI();
}
